-- AlterTable
ALTER TABLE "Todo" ADD COLUMN     "userId" INTEGER,
ALTER COLUMN "deadline" DROP NOT NULL,
ALTER COLUMN "deadline" DROP DEFAULT;

-- AddForeignKey
ALTER TABLE "Todo" ADD CONSTRAINT "Todo_userId_fkey" FOREIGN KEY ("userId") REFERENCES "User"("id") ON DELETE SET NULL ON UPDATE CASCADE;
